### ISSUE TITLE
Satzanfang mit Großbuchstaben

### ISSUE THREAD

**Issue by MegaV0lt** [vdr-projects/vdr-plugin-epgsearch#11]
https://github.com/vdr-projects/vdr-plugin-epgsearch/blob/7f7f9f6569bd50946166fe23463879c16378b651/po/de_DE.po#L1301
Bitte das Erste Wort mit großem **W** schreiben

Sieht komisch aus in eMail
![Auswahl_023](https://github.com/vdr-projects/vdr-plugin-epgsearch/assets/2804301/81cf9625-4e53-45a7-bc48-0003c7b72831)

**Comment by tomjfr** [comment]
Fixed
