### ISSUE TITLE
Parsing Error with multiple colons

### ISSUE THREAD

**Issue by FireFlyVDR** [vdr-projects/vdr-plugin-epgsearch#14]
If the title contains more than one colon the parser fails and the line in the whats_on menu stays empty. In the log appear message like:
```error parsing '%time_w% %time_d%#011%time%#011$status$#011Berufung? Deutschlands wichtigste Jobs%colon% Müllwerker:innen ~ %subtitle%'```
```error parsing '%time_w% %time_d%#011%time%#011$status$#011Berufung? Deutschlands wichtigste Jobs%colon% Forstwirt:innen ~ %subtitle%'```

The attached patch fixes this.

[epgsearch-2.4.1_-fix_parser_error_multiple_colon_whatson.diff.txt](https://github.com/vdr-projects/vdr-plugin-epgsearch/files/11667430/epgsearch-2.4.1_-fix_parser_error_multiple_colon_whatson.diff.txt)

**Comment by tomjfr** [comment]
Will be in the next update
